# Generated by Django 5.1 on 2024-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='status',
            field=models.BinaryField(default=False),
        ),
    ]
