# Generated by Django 5.1 on 2024-08-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skills_employee_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='noti',
            field=models.BinaryField(default=False),
        ),
    ]
