# Generated by Django 5.1 on 2024-08-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_job_noti'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experiance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
