# Generated by Django 5.1 on 2024-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_job_experiance_job_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='noti',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('N', 'None')], default='N', max_length=1),
        ),
    ]
