# Generated by Django 5.1 on 2024-08-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_job_noti_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='noti',
            field=models.BinaryField(default=False),
        ),
    ]
