# Generated by Django 5.1 on 2024-08-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_job_noti'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fromd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tod',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
