# Generated by Django 5.1 on 2024-08-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_job_description_job_education_job_fromd_job_tod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='section',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
