# Generated by Django 5.1 on 2024-09-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_type_alter_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='section',
        ),
        migrations.AlterField(
            model_name='job',
            name='approval',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
