# Generated by Django 5.1 on 2024-09-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_job_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approval',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
