# Generated by Django 5.1 on 2024-09-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_job_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='save',
            field=models.BinaryField(default=False),
        ),
    ]
