# Generated by Django 5.1 on 2024-09-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_job_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='save',
            field=models.BooleanField(default=False),
        ),
    ]
