# Generated by Django 5.1 on 2024-09-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_job_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='save',
            new_name='is_saved',
        ),
    ]
