# Generated by Django 5.1 on 2024-09-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_save_job_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_saved',
        ),
    ]
