# Generated by Django 5.1 on 2024-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_job_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_saved',
            field=models.BinaryField(default=False),
        ),
    ]
