from django.urls import path
from .import views

urlpatterns = [
   
   path('ajax/check_username/', views.check_username, name='check_username'),
   path('ajax/check_email/', views.check_email, name='check_email'),
   path('signup/', views.signup, name='signup'),
   path('login', views.login_view, name='login'),
   path('employer_dashboard/', views.employer_dashboard, name='employer_dashboard'),
   path('jobseeker_dashboard/', views.jobseeker_dashboard, name='jobseeker_dashboard'),
   path('complete_registration/', views.complete_registration, name='complete_registration'),
   path('add_education/', views.add_education, name='add_education'),
   path('add_experience/', views.add_experience, name='add_experience'),
   path('add_skills/', views.add_skills, name='add_skills'),
   path('profile/', views.profile, name='profile'),
   path('complete_employer_registration/', views.complete_employer_registration, name='complete_employer_registration'),
   path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
   path('manage-sections/', views.manage_sections, name='manage_sections'),
   path('manage-types/', views.manage_types, name='manage_types'),
   path('add-section/', views.add_section, name='add_section'),
   path('add-type/', views.add_type, name='add_type'),
   path('lgout',views.lgout,name='lgout'),
   path('add-job/', views.add_job, name='add_job'),
   path('pending-jobs/', views.pending_jobs, name='pending_jobs'),
   path('xapprove-job/<int:job_id>/', views.xapprove_job, name='xapprove_job'),
   path('xreject-job/<int:job_id>/', views.xreject_job, name='xreject_job'),
   path('jobseeker-dashboard/', views.jobseeker_dashboard, name='jobseeker_dashboard'),
   path('matching-jobs/', views.matching_jobs, name='matching_jobs'),
   path('apply-job/<int:job_id>/', views.apply_job, name='apply_job'),
   path('job/<int:job_id>/', views.view_job_details, name='view_job_details'),
   path('employer-job-applicants/', views.employer_job_applicants, name='employer_job_applicants'),
   path('view-employee-details/<int:employee_id>/', views.view_employee_details, name='view_employee_details'),
   path('filtered-jobs/', views.filtered_jobs, name='filtered_jobs'),
   path('home',views.home,name='home'),
   
   path('',views.hoshome,name='hoshome'),
   path('ufiltered-jobs/', views.ufiltered_jobs, name='ufiltered_jobs'),
   path('employee/jobs/', views.employee_jobs, name='employee_jobs'),
   path('userjobdetail/<int:job_id>/', views.job_detail, name='job_detail'),
   path('employer/jobs/', views.employer_job_list, name='employer_job_list'),
   path('employer/jobs/edit/<int:job_id>/', views.employer_edit_job, name='employer_edit_job'),
   path('employer/jobs/delete/<int:job_id>/', views.employer_delete_job, name='employer_delete_job'),
   path('employer/noti/', views.xemployer_job_list, name='xemployer_job_list'),
   path('acknowledge-job/<int:job_id>/', views.acknowledge_job, name='acknowledge_job'),
   path('candidate_details', views.candidate_details, name='candidate_details'),
   path('approve-job/<int:job_id>/', views.approve_job, name='approve_job'),
   path('reject-job/<int:job_id>/', views.reject_job, name='reject_job'),
   path('pending-job/<int:job_id>/', views.mark_as_pending, name='mark_as_pending'),
   path('view_profile/', views.view_profile, name='view_profile'),
   path('profile/edit/', views.edit_profile, name='edit_profile'),
   path('employer-job-status/', views.employer_job_status, name='employer_job_status'),
   path('adminjobsss/<int:job_id>/', views.job_details, name='job_details'),
   path('base',views.base,name='base'),
   path('delete-section/<int:section_id>/', views.delete_section, name='delete_section'),
   path('delete_type/<int:type_id>/', views.delete_type, name='delete_type'),
   path('employers/', views.list_employers, name='list_employers'),
   path('delete_employer/<int:employer_id>/', views.delete_employer, name='delete_employer'),
   path('save-job/<int:job_id>/', views.save_job, name='save_job'),
   path('saved-jobs/', views.saved_jobs, name='saved_jobs'),
   path('save_detail/<int:job_id>/', views.save_details, name='save_details'),
   path('apply-save/<int:job_id>/', views.apply_save, name='apply_save'),
   path('undo-save/<int:job_id>/', views.undo_save, name='undo_save'),
   path('employer/all/', views.employer_all_list, name='employer_all_list'),
   path('job_det/<int:job_id>/', views.job_det, name='job_det'),

]